name: Deploy on Open Pull Request

on:
  pull_request:
    types:
      - opened
    branches:
      - main
      - crud-rds

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.17

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Salutation
        run: |
          echo 'print("Hello World")' | python3
          
      - name: Deploy Your Application
        run: |
          # Add your deployment commands here
          # For example, you might use a script to deploy your Flask app
          python3 ./crud-rds-mysql.py
